[package]
name = "rsa_demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rsa = "0.9.6"
base64 = "0.22.0"
rand = "0.8.5"
openssl-sys = "0.9"
openssl = "0.10"
