[package]
name = "ini"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[[test]]
name = "ini_unittest"
path = "src/ini_unittest.rs"

[dependencies]
rust-ini = "0.21"
chrono = "0.4"
