[package]
name = "file_server"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-files = "0.6"
actix-multipart = "0.7"
actix-web = "4.9"
futures-util = "0.3"
tokio = { version = "1", features = ["full"] }
