name: Build toolchain

on: 
  # 清理 Cache 后触发
  workflow_run: 
    workflows: [Cleanup caches by a branch]
    types: completed
  # 手动触发
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
          - macos-latest
          - ubuntu-latest

    steps:
      - name: Install dependencies on windows
        if: startsWith(matrix.os, 'windows')
        shell: bash
        run: |
          vcpkg integrate install
          vcpkg install openssl --triplet x64-windows-static-md
      - name: Install dependencies on macos
        if: startsWith(matrix.os, 'macos')
        shell: bash
        run: |
          brew install openssl@3
      - name: Install dependencies on ubuntu
        if: startsWith(matrix.os, 'ubuntu')
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install pkg-config libssl-dev

      - name: cache windows vcpkg
        if: startsWith(matrix.os, 'windows')
        uses: actions/cache/save@v3
        with: 
          path: C:\vcpkg\installed
          key: ${{ runner.os }}-vcpkg-installed-${{ matrix.os }}
      - name: cache macos or ubuntu vcpkg
        if: startsWith(matrix.os, 'macos') || startsWith(matrix.os, 'ubuntu')
        uses: actions/cache/save@v3
        with: 
          path: /usr/local/share/vcpkg/installed
          key: ${{ runner.os }}-vcpkg-installed-${{ matrix.os }}

